version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/projectdir
hooks:
  BeforeInstall: 
    - location: first.sh
      timeout: 300
  AfterInstall:
    - location: second.sh
      timeout: 300
 
